name: Lint Checks

on:
  pull_request:
    branches:
      - development

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          composer install
          npm install
          npm install @wordpress/scripts --save-dev

      - name: Validate Composer configuration
        run: |
          composer validate | grep -q 'ERROR' && exit 1

      - name: Run PHPCS
        run: |
          composer phpcs | grep -q 'ERROR' && exit 1

      - name: Lint CSS
        run: |
          npm run lint:css --if-present || exit 1

      - name: Lint JS
        run: |
          npm run lint:js --if-present || exit 1

      - name: Run tests
        run: |
          npm run test || exit 1