name: Production Checks

on:
    pull_request:
        branches:
            - development

jobs:
    production:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: |
                  composer install
                  npm install
                  npm install @wordpress/scripts --save-dev

    validate:
        runs-on: ubuntu-latest
        needs: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate Composer
              run: composer validate

    phpcs:
        runs-on: ubuntu-latest
        needs: validate
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run PHP_CodeSniffer
              run: composer phpcs -- --warning-severity=1

    lint_css:
        runs-on: ubuntu-latest
        needs: phpcs
        steps:
            - name: Install Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  composer install
                  npm install
                  npm install @wordpress/scripts --save-dev

            - name: Lint CSS
              run: npm run lint:css

    lint_js:
        runs-on: ubuntu-latest
        needs: lint_css
        steps:
            - name: Install Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  composer install
                  npm install
                  npm install @wordpress/scripts --save-dev

            - name: Lint JS
              run: npm run lint:js -- --max-warnings=0

    test:
        runs-on: ubuntu-latest
        needs: lint_js
        steps:
            - name: Run Tests
              run: npm run test
