name: Production Checks

on:
  pull_request:
    branches:
      - development

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install
          npm install
          npm install @wordpress/scripts --save-dev

      - name: Run production checks
        run: |
          composer validate
          composer phpcs
          npm run lint:css
          npm run lint:js
          npm run test