name: Production Checks

on:
  pull_request:
    branches:
      - development

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          composer install
          npm install
          npm install @wordpress/scripts --save-dev

      - name: Run production checks
        run: |
          composer validate || exit 1
          composer phpcs || exit 1
          npm run lint:css || exit 1
          npm run lint:js || exit 1
          npm run test || exit 1