name: WordPress PHPUnit Tests

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        # Update the specific version of MySQL to match the version used on your server.
        image: mysql:8
        env:
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: PHP Setup 
        uses: shivammathur/setup-php@v2
        with:
          # Update the specific version of PHP to match the version used on your server.
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

      - name: Create WordPress test database
        run: bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          WP_DB_HOST: 127.0.0.1:${{ job.services.mysql.ports[3306] }}