name: WordPress PHPUnit Tests

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        # Update the specific version of MySQL to match the version used on your server.
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_HOST: 127.0.0.1
          DOCKER_TOKEN: ${DOCKER_TOKEN}  # Reference your token here
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: PHP Setup 
        uses: shivammathur/setup-php@v2
        with:
          # Update the specific version of PHP to match the version used on your server.
          php-version: '7.4'

      - name: Install dependencies
        run: composer install
      
      - name: Wait for MySQL
        run: |
                  for i in {1..30}; do
                      if mysqladmin ping -h 127.0.0.1 --silent; then
                         echo $(mysqladmin ping -h 127.0.0.1)
                         break
                      fi
                      echo "Waiting for MySQL..."
                      sleep 2
                  done

      - name: Configure Tests
        run: composer test-setup

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
        env:
          WP_DB_USER: wp_test
          WP_DB_PASS: password
          WP_DB_NAME: wp_tests_db
          WP_DB_HOST: 127.0.0.1:${{ job.services.mysql.ports[3306] }}