name: WordPress PHPUnit Tests

on:
  pull_request:
    branches:
      - development
      
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Wait for MySQL
        run: |
          while ! mysql -h 127.0.0.1 -u root --password='' -e "SELECT 1"; do
            sleep 1
          done

      - name: Create WordPress test database
        run: bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist